{
 "title": "Ceph",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "cloud", "label": "service", "query": "label_values(service)" }
  ]
 },
 "panels": [
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numOsdUp\",service=\"$cloud\"})",
     "legendFormat": "UP"
    },
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numOsd\",service=\"$cloud\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "MONs up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numMon\",service=\"$cloud\"})",
     "legendFormat": "UP"
    },
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numMonQuorum\",service=\"$cloud\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Num PGs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numPgActiveClean\",service=\"$cloud\"})",
     "legendFormat": "Active/clean"
    },
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numPg\",service=\"$cloud\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Num Objects",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numObject\",service=\"$cloud\"})-avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numObjectDegraded\",service=\"$cloud\"})+avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numObjectMisplaced\",service=\"$cloud\"})+avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numObjectUnfound\",service=\"$cloud\"})",
     "legendFormat": "Healthy"
    },
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numObject\",service=\"$cloud\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Num Pools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.numPool\",service=\"$cloud\"})",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.osdBytesUsed\",service=\"$cloud\"})/3",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(collectd_ceph_ceph_bytes{type_instance=\"Cluster.osdBytes\",service=\"$cloud\"})/3",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(collectd_ceph_ceph_rate_total{type_instance=\"Osd.opInBytes\",service=\"$cloud\"}[2m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum by (service) (rate(collectd_ceph_ceph_rate_total{type_instance=\"Osd.opOutBytes\",service=\"$cloud\"}[2m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Cluster IOPs",
   "type": "graph",
   "description": "System load averaged against CPU count",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(collectd_ceph_ceph_rate_total{type_instance=\"Osd.op\",service=\"$cloud\"}[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (service) (rate(collectd_ceph_ceph_rate_total{type_instance=\"Osd.opR\",service=\"$cloud\"}[2m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum by (service) (rate(collectd_ceph_ceph_rate_total{type_instance=\"Osd.opW\",service=\"$cloud\"}[2m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Cluster I/O Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (collectd_ceph_ceph_latency{type_instance=\"Osd.opRLatency\",service=\"$cloud\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum by (service) (collectd_ceph_ceph_latency{type_instance=\"Osd.opWLatency\",service=\"$cloud\"})",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}