{
 "title": "Cloud Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Aggregate CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_cpu_percent{type_instance!=\"idle\"}) / count by (host) (sum by (host,type_instance) (collectd_cpu_percent{type_instance!=\"idle\"}))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Aggr. CPU Usage by Type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_cpu_percent{type_instance!=\"idle\"}) by (host,type_instance) / count(collectd_cpu_percent) by (host,type_instance)",
     "legendFormat": "{{ host }} [{{type_instance}}]"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{severity=~\"critical|warning\", alertstate=~\"firing|pending\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_memory{type_instance=\"used\"}) / sum by (host) (collectd_memory)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "description": "System load averaged against CPU count",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "collectd_load_shortterm / collectd_cpu_count",
     "legendFormat": "short term {{ host }}"
    },
    {
     "expr": "collectd_load_midterm / collectd_cpu_count",
     "legendFormat": "mid term {{ host }}"
    },
    {
     "expr": "collectd_load_longterm / collectd_cpu_count",
     "legendFormat": "long term {{ host }}"
    }
   ]
  },
  {
   "title": "Interface Data",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_octets_rx_total{plugin_instance!=\"lo\"}[30s])",
     "legendFormat": "Rx {{ host }} [interface: {{plugin_instance}} ]"
    },
    {
     "expr": "rate(collectd_interface_if_octets_tx_total{plugin_instance!=\"lo\"}[30s])",
     "legendFormat": "Tx {{ host }} [interface: {{plugin_instance}} ]"
    }
   ]
  },
  {
   "title": "Interface Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "pps", "label": "Error Rate" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (rate(collectd_interface_if_errors_rx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*|vlan.*\"}[1m]))",
     "legendFormat": "Rx {{ host }}"
    },
    {
     "expr": "sum by (host) (rate(collectd_interface_if_errors_tx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*|vlan.*\"}[1m]))",
     "legendFormat": "Tx {{ host }}"
    }
   ]
  },
  {
   "title": "Interface Dropped Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "pps", "label": "Dropped Rate" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (rate(collectd_interface_if_dropped_rx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*|vlan.*\"}[1m]))",
     "legendFormat": "Rx {{ host }}"
    },
    {
     "expr": "sum by (host) (rate(collectd_interface_if_dropped_tx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*|vlan.*\"}[1m]))",
     "legendFormat": "Tx {{ host }}"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (host) (collectd_cpu_percent{type_instance!=\"idle\"}) / count by (host) (sum by (host,type_instance) (collectd_cpu_percent{type_instance!=\"idle\"}))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by (host) (collectd_memory{type_instance=\"used\"}) / sum by (host) (collectd_memory)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Inode Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by (host) (collectd_df_df_inodes{type_instance=\"used\"}) / sum by (host) (collectd_df_df_inodes)",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}