{
 "title": "NFV Traffic",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Physical Bonded Links",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_rx_octets_total{plugin_instance=~\"br-link.+phy.*\"}[1m])",
     "legendFormat": "Rx {{ plugin_instance }} on {{ host }}"
    },
    {
     "expr": "rate(collectd_ovs_stats_if_tx_octets_total{plugin_instance=~\"br-link.+phy.*\"}[1m])",
     "legendFormat": "Tx {{ plugin_instance }} on {{ host }}"
    }
   ]
  },
  {
   "title": "Interface packets-per-second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_packets_rx_total{plugin_instance!=\"lo\"}[1m])",
     "legendFormat": "Rx {{ plugin_instance }} on {{ host }}"
    },
    {
     "expr": "rate(collectd_interface_if_packets_tx_total{plugin_instance!=\"lo\"}[1m])",
     "legendFormat": "Tx {{ plugin_instance }} on {{ host }}"
    }
   ]
  },
  {
   "title": "Interface Dropped Packet Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_dropped_rx_total{plugin_instance!=\"lo\",plugin_instance!=\"br-int\"}[1m])",
     "legendFormat": "Rx {{ plugin_instance }} on {{ host }}"
    },
    {
     "expr": "rate(collectd_interface_if_dropped_tx_total{plugin_instance!=\"lo\",plugin_instance!=\"br-int\"}[1m])",
     "legendFormat": "Tx {{ plugin_instance }} on {{ host }}"
    }
   ]
  },
  { "title": "Alert Status", "type": "alertlist", "gridPos": { "h": 24, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Interface Error Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_errors_rx_total[1m])",
     "legendFormat": "Rx {{plugin_instance}} on {{ host }}"
    },
    {
     "expr": "rate(collectd_interface_if_errors_tx_total[1m])",
     "legendFormat": "Tx {{plugin_instance}} on {{ host }}"
    }
   ]
  },
  {
   "title": "Virtual Machine Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_virt_if_octets_rx_total[1m])",
     "legendFormat": "Rx {{type_instance}} on {{host}}"
    },
    {
     "expr": "rate(collectd_virt_if_octets_tx_total[1m])",
     "legendFormat": "Tx {{type_instance}} on {{host}}"
    }
   ]
  },
  {
   "title": "VM packets-per-second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_virt_if_packets_rx_total[1m])",
     "legendFormat": "Rx {{ type_instance }} on {{ host }}"
    },
    {
     "expr": "rate(collectd_virt_if_packets_tx_total[1m])",
     "legendFormat": "Tx {{ type_instance }} on {{ host }}"
    }
   ]
  },
  {
   "title": "Virtual Interface Dropped Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_virt_if_dropped_rx_total[1m])",
     "legendFormat": "Rx {{ type_instance }} on {{ host }}"
    },
    {
     "expr": "rate(collectd_virt_if_dropped_tx_total[1m])",
     "legendFormat": "Tx {{ type_instance }} on {{ host }}"
    }
   ]
  },
  {
   "title": "Virtual Interface Error Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_virt_if_errors_rx_total[1m])",
     "legendFormat": "Rx {{type_instance}} on {{host}}"
    },
    {
     "expr": "rate(collectd_virt_if_errors_tx_total[1m])",
     "legendFormat": "Tx {{type_instance}} on {{host}}"
    }
   ]
  },
  {
   "title": "DPDK Link Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_rx_octets_total{plugin_instance=~\"br-link.*dpdk.*\"}[1m])",
     "legendFormat": "Rx {{plugin_instance}} on {{ host }}"
    },
    {
     "expr": "rate(collectd_ovs_stats_if_tx_octets_total{plugin_instance=~\"br-link.*dpdk.*\"}[1m])",
     "legendFormat": "Tx {{plugin_instance}} on {{ host }}"
    }
   ]
  },
  {
   "title": "DPDK packets-per-second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_packets_rx_total{plugin_instance=~\"br-link.+dpdk.*\"}[1m])",
     "legendFormat": "Rx {{ type_instance }}"
    },
    {
     "expr": "rate(collectd_ovs_stats_if_tx_packets_total{plugin_instance=~\"br-link.+dpdk.*\"}[1m])",
     "legendFormat": "Tx {{ type_instance }}"
    }
   ]
  },
  {
   "title": "DPDK Dropped Packet Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_dropped_rx_total{plugin_instance=~\"br-link.+dpdk.*\"}[1m])",
     "legendFormat": "Rx {{ plugin_instance }} on {{ host }}"
    },
    {
     "expr": "rate(collectd_ovs_stats_if_dropped_tx_total{plugin_instance=~\"br-link.+dpdk.*\"}[1m])",
     "legendFormat": "Tx {{ plugin_instance }} on {{ host }}"
    }
   ]
  },
  {
   "title": "DPDK Link Error Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 20 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_ovs_stats_if_rx_errors_total{plugin_instance=~\"br-link.+dpdk.*\"}[1m])",
     "legendFormat": "Rx {{ type_instance }} on interface {{ plugin_instance }}"
    },
    {
     "expr": "rate(collectd_ovs_stats_if_rx_errors_total{plugin_instance=~\"br-link.+dpdk.*\"}[1m])",
     "legendFormat": "Tx {{ type_instance }} on interface {{ plugin_instance }}"
    }
   ]
  }
 ]
}