{
 "title": "Infrastructure Node Simplified",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hosts", "label": "nodes", "query": "label_values(host)" }
  ]
 },
 "panels": [
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{host=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPUs cores on node",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(collectd_cpu_percent{host=\"$hosts\"}) by (plugin_instance))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Total amount of memory on node",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(collectd_memory{host=\"$hosts\"})",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  {
   "title": "Physical Interfaces Ingress Errors",
   "type": "singlestat",
   "description": "Disclaimer: query contains a set of typical hardware interfaces seen on Linux systems. Some unrecognized interfaces may not be included in the query.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(collectd_interface_if_errors_rx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*\",host=\"$hosts\"})",
     "legendFormat": "{{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Physical Interfaces Egress Errors",
   "type": "singlestat",
   "description": "Disclaimer: query contains a set of typical hardware interfaces seen on Linux systems. Some unrecognized interfaces may not be included in the query.",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(collectd_interface_if_errors_tx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*\",host=\"$hosts\"})",
     "legendFormat": "{{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(collectd_cpu_percent{type_instance!=\"idle\", host=\"$hosts\"}) / count(sum by (type_instance) (collectd_cpu_percent{type_instance!=\"idle\",host=\"$hosts\"}))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "sum(collectd_memory{type_instance=\"used\",host=\"$hosts\"})/ sum(collectd_memory{host=\"$hosts\"})",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  {
   "title": "Inode Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sum(collectd_df_df_inodes{type_instance=\"used\", host=\"$hosts\"}) / sum(collectd_df_df_inodes{host=\"$hosts\"})"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "targets": [
    {
     "expr": "sum(collectd_df_df_complex{plugin_instance!~\"devtmpfs|overlay|shm|tmpfs\",type_instance!=\"free\",host=\"$hosts\"})/sum(collectd_df_df_complex{plugin_instance!~\"devtmpfs|overlay|shm|tmpfs\",host=\"$hosts\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Shows whether any metrics at all were received for this Node during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "absent({host = '$hosts'}) or label_replace(vector(0), \"host\", \"$hosts\", \"host\", \".*\")"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Time node has been operational",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_uptime{host=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "Huge Pages Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(collectd_hugepages_vmpage_number{type_instance=\"used\",host=\"$hosts\"})",
     "legendFormat": "{{hugepages}}"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "singlestat",
   "description": "Aproxement total disk space available on to the root device on this node.\n\nDisclaimer: this query excludes the temporary filesystems (tmpfs,devtmpfs,overlay). Thus, if swap storage is used, these file systems may use disk space, causing this result to appear smaller than it should. ",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(collectd_df_df_complex{plugin_instance!~\"devtmpfs|overlay|shm|tmpfs\",host=\"$hosts\"})",
     "legendFormat": "{{df}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "On Linux, load average represents the average number of running and uninterruptable processes residing in the kernel's execution queue. \n\nTypically, short term, midterm, and longterm series give running averages of 1m, 5m, and 15m, respectively. ",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "collectd_load_shortterm{host=\"$hosts\"}",
     "legendFormat": "short term"
    },
    {
     "expr": "collectd_load_midterm{host=\"$hosts\"}",
     "legendFormat": "mid term"
    },
    {
     "expr": "collectd_load_longterm{host=\"$hosts\"}",
     "legendFormat": "long term"
    }
   ]
  },
  {
   "title": "Aggregate CPU Usage",
   "type": "graph",
   "description": "Average non-idle CPU activity of all cores on node",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_cpu_percent{type_instance!=\"idle\", host=\"$hosts\"}) / count(sum by (type_instance) (collectd_cpu_percent{type_instance!=\"idle\",host=\"$hosts\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Aggr. CPU Usage by Type",
   "type": "graph",
   "description": "Shows average time spent for each activity across all cores",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_cpu_percent{type_instance!=\"idle\", host=\"$hosts\"}) by (type_instance) / count(collectd_cpu_percent{host=\"$hosts\"}) by (type_instance)",
     "legendFormat": "{{type_instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory used on node",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_memory{type_instance=\"used\",host=\"$hosts\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Interface Data",
   "type": "graph",
   "description": "Disclaimer: query contains a set of typical hardware interfaces seen on Linux systems. Some unrecognized interfaces may not be included in the query.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_octets_rx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Rx {{plugin_instance}}"
    },
    {
     "expr": "rate(collectd_interface_if_octets_tx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Tx {{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Interfaces Packets",
   "type": "graph",
   "description": "Disclaimer: query contains a set of typical hardware interfaces seen on Linux systems. Some unrecognized interfaces may not be included in the query.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_packets_rx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Rx {{plugin_instance}}"
    },
    {
     "expr": "rate(collectd_interface_if_packets_tx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Tx {{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Physical Interfaces Error Rates",
   "type": "graph",
   "description": "Disclaimer: query contains a set of typical hardware interfaces seen on Linux systems. Some unrecognized interfaces may not be included in the query.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_errors_rx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*\",host=\"$hosts\"}[10m])",
     "legendFormat": "Rx {{plugin_instance}}"
    },
    {
     "expr": "rate(collectd_interface_if_errors_tx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*\",host=\"$hosts\"}[10m])",
     "legendFormat": "Tx {{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Physical Interfaces Drop Rate",
   "type": "graph",
   "description": "Disclaimer: query contains a set of typical hardware interfaces seen on Linux systems. Some unrecognized interfaces may not be included in the query.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_dropped_rx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*\",host=\"$hosts\"}[10m])",
     "legendFormat": "Rx {{plugin_instance}}"
    },
    {
     "expr": "rate(collectd_interface_if_dropped_tx_total{plugin_instance=~\"eth.*|wlan.*|wlp.*|ens.*|enp.*\",host=\"$hosts\"}[10m])",
     "legendFormat": "Tx {{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Aggregate Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (type_instance) (collectd_df_df_complex{plugin_instance!~\"devtmpfs|overlay|shm|tmpfs\",type_instance!~\"free\",host=\"$hosts\"})",
     "legendFormat": "{{type_instance}}"
    }
   ]
  },
  {
   "title": "Disk Traffic",
   "type": "graph",
   "description": "10m rolling average",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_disk_disk_octets_read_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(collectd_disk_disk_octets_write_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "graph",
   "description": "Approximate percentage of total disk bandwidth being used.\n\nWeighted I/O includes the backlog that may be accumulating.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_disk_disk_io_time_io_time_total{host=\"$hosts\"}[1h]))/1000",
     "legendFormat": "i/o"
    },
    {
     "expr": "sum(rate(collectd_disk_disk_io_time_weighted_io_time_total{host=\"$hosts\"}[1h]))/1000",
     "legendFormat": "weighted i/o"
    }
   ]
  },
  {
   "title": "Operations/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_disk_disk_ops_read_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(collectd_disk_disk_ops_write_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Average I/O Operation Time",
   "type": "graph",
   "description": "Average time each I/O operation took to complete. Per the collectd disk plugin docs (https://collectd.org/wiki/index.php/Plugin:Disk), this average is not very accurate.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_disk_disk_time_read_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(collectd_disk_disk_time_write_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "write"
    }
   ]
  }
 ]
}