{
 "title": "Smart Gateway Tracker",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Collector Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "collectd memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "collectd_libpodstats_pod_memory{plugin_instance=\"collectd\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "ceilometer memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "collectd_libpodstats_pod_memory{plugin_instance=~\"ceilometer.*\"}",
     "legendFormat": "{{ host }} ({{ plugin_instance}})"
    }
   ]
  },
  {
   "title": "bus memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "collectd_libpodstats_pod_memory{plugin_instance=~\"rabbitmq.*|metrics_qdr\"}",
     "legendFormat": "{{ host }} ({{ plugin_instance}})"
    }
   ]
  },
  { "title": "Messages Received", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Collectd Message Recv Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(sg_total_collectd_msg_received_count[1m])",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Ceilometer Message Recv Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(sg_total_ceilometer_msg_received_count[1m])  ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Sensubility Message Recv Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "rate(sg_total_sensubility_msg_received_count[1m])",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Collectd Message Recv Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sg_total_collectd_msg_received_count",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Ceilometer Message Recv Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sg_total_ceilometer_msg_received_count",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Sensubility Message Recv Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sg_total_sensubility_msg_received_count",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  { "title": "Scrape Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Samples Scraped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    { "expr": "scrape_samples_scraped", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "Series Added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    { "expr": "scrape_series_added", "legendFormat": "{{ service }}" }
   ]
  },
  { "title": "Decoding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Collectd Metrics Decode Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sg_total_collectd_metric_decode_count[1m])",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Ceilometer Metrics Decode Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sg_total_ceilometer_metric_decode_count[1m])",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Sensubility Metrics Decode Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sg_total_sensubility_metric_decode_count[1m])",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Collectd Metric Decode Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sg_total_collectd_msg_received_count",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Ceilometer Metric Decode Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sg_total_ceilometer_msg_received_count",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Sensubility Metric Decode Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sg_total_sensubility_msg_received_count",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Collectd Metric Decoding Percentage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sg_total_collectd_metric_decode_count / (sg_total_collectd_metric_decode_count + sg_total_collectd_metric_decode_error_count)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Ceilometer Metric Decoding Percentage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sg_total_ceilometer_metric_decode_count / (sg_total_ceilometer_metric_decode_count + sg_total_ceilometer_metric_decode_error_count)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Sensubility Metric Decoding Percentage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sg_total_sensubility_metric_decode_count / (sg_total_sensubility_metric_decode_count + sg_total_sensubility_metric_decode_error_count)",
     "legendFormat": "{{ service }}"
    }
   ]
  }
 ]
}