{
 "title": "Virtual Machine View",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "project", "label": "project", "query": "label_values(project)" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Virtual Machine Instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(avg by (project,resource) (ceilometer_cpu{project=\"$project\"}))"
    }
   ]
  },
  {
   "title": "Recent Events",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event_type",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "payload.traits.project_id: $project",
     "timeField": "payload.generated"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg by (resource) (ceilometer_cpu{project=\"$project\"})"
    }
   ]
  },
  {
   "title": "VM CPU %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(collectd_virt_percent, \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "{{resource}} on {{ host }}"
    }
   ]
  },
  {
   "title": "CPU Time for Instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "(avg by (resource,project) (rate(ceilometer_cpu{project=\"$project\"}[1m])))",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "VM Memory Utilization (Allocated)",
   "type": "graph",
   "description": "Memory utilization of that allocated to the virtual machine.",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(label_replace(collectd_virt_memory, \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") / 1000000) / on (resource) group_left (project) (avg by (resource,project) (ceilometer_memory_usage{project=\"$project\"}))",
     "legendFormat": "{{ resource }} [{{ type_instance }}] on {{ host }}"
    }
   ]
  },
  {
   "title": "VM Network Throughput Rate",
   "type": "graph",
   "description": "Virtual machine network throughput rate (in bytes)",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(collectd_virt_if_octets_rx_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Rx {{ resource }} interface {{ type_instance }}"
    },
    {
     "expr": "label_replace(rate(collectd_virt_if_octets_tx_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Tx {{ resource }} interface {{ type_instance }}"
    }
   ]
  },
  {
   "title": "VM Network Dropped Packet Rate",
   "type": "graph",
   "description": "Virtual machine network dropped packet rate (in packets-per-second)",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(collectd_virt_if_dropped_rx_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Rx {{ resource }} interface {{ type_instance }}"
    },
    {
     "expr": "label_replace(rate(collectd_virt_if_dropped_tx_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Tx {{ resource }} interface {{ type_instance }}"
    }
   ]
  },
  {
   "title": "VM Network Error Rate",
   "type": "graph",
   "description": "Virtual machine network error rate (in packets-per-second)",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(collectd_virt_if_errors_rx_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Rx {{ resource }} interface {{ type_instance }}"
    },
    {
     "expr": "label_replace(rate(collectd_virt_if_errors_tx_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Tx {{ resource }} interface {{ type_instance }}"
    }
   ]
  },
  {
   "title": "VM Disk Throughput Rate",
   "type": "graph",
   "description": "Virtual machine disk throughput rate (in bytes)",
   "gridPos": { "h": 5, "w": 9, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(collectd_virt_disk_octets_read_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Read {{ resource }} disk {{ type_instance }}"
    },
    {
     "expr": "label_replace(rate(collectd_virt_disk_octets_write_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Write {{ resource }} disk {{ type_instance }}"
    }
   ]
  },
  {
   "title": "VM Disk Operations Rate",
   "type": "graph",
   "description": "Virtual machine disk operations rate (in operations/second)",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(collectd_virt_disk_ops_read_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Read {{ resource }} disk {{ type_instance }}"
    },
    {
     "expr": "label_replace(rate(collectd_virt_disk_ops_write_total[1m]), \"resource\", \"$1\", \"plugin_instance\", \"(.*)\") + on (resource) group_left(project) (avg by (resource,project) (ceilometer_cpu{project=\"$project\"}) * 0)",
     "legendFormat": "Write {{ resource }} disk {{ type_instance }}"
    }
   ]
  }
 ]
}