{
 "title": "Cloud View",
 "tags": [ "cloud-dashboards" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "clouds",
    "label": "cloud",
    "query": {
     "query": "label_values(collectd_cpu_percent, service)"
    }
   },
   {
    "name": "projects",
    "query": {
     "query": "label_values(ceilometer_cpu{service=~\".+-$clouds-.+\"},project)"
    }
   },
   {
    "name": "top",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": " avg(sensubility_container_health_status{process=\"glance_api\", service=~\".+-$clouds-.+\"})",
     "legendFormat": "glance_api"
    },
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(sensubility_container_health_status{process=\"nova_api\", service=~\".+-$clouds-.+\"})",
     "legendFormat": "nova_api",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "startsAt"
    },
    {
     "expr": "avg(sensubility_container_health_status{process=\"heat_api\", service=~\".+-$clouds-.+\"})",
     "legendFormat": "heat_api"
    },
    {
     "expr": "avg(sensubility_container_health_status{process=\"neutron_api\", service=~\".+-$clouds-.+\"})",
     "legendFormat": "neutron_api"
    },
    {
     "expr": "avg(sensubility_container_health_status{process=\"placement_api\", service=~\".+-$clouds-.+\"})",
     "legendFormat": "placement_api"
    }
   ]
  },
  {
   "title": "Top $top Memory Consumers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk($top, sum by (plugin_instance, host) (collectd_libpodstats_pod_memory{service=~\".+-$clouds-.+\"}))",
     "legendFormat": "{{plugin_instance}} on {{host}}"
    }
   ]
  },
  {
   "title": "Top $top CPU Consumers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($top, avg_over_time(collectd_libpodstats_pod_cpu_percent{service=~\".+-$clouds-.+\"}[10m]))",
     "legendFormat": "{{plugin_instance}} on {{host}}"
    }
   ]
  },
  {
   "title": "Uptime placement_api",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(sensubility_container_health_status{process=\"placement_api\", service=~\".+-$clouds-.+\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "startsAt"
    }
   ]
  },
  {
   "title": "Uptime neutron_api",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(sensubility_container_health_status{process=\"neutron_api\", service=~\".+-$clouds-.+\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "startsAt"
    }
   ]
  },
  {
   "title": "Uptime heat_api",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(sensubility_container_health_status{process=\"heat_api\", service=~\".+-$clouds-.+\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "startsAt"
    }
   ]
  },
  {
   "title": "Uptime nova_api",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(sensubility_container_health_status{process=\"nova_api\", service=~\".+-$clouds-.+\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "startsAt"
    }
   ]
  },
  {
   "title": "Uptime glance_api",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "startsAt", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(sensubility_container_health_status{process=\"glance_api\", service=~\".+-$clouds-.+\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "startsAt"
    }
   ]
  },
  { "title": "Service Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Horizon CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "collectd_libpodstats_pod_cpu_percent{plugin_instance=\"horizon\", service=~\".+-$clouds-.+\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Horizon Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "collectd_libpodstats_pod_memory{plugin_instance=\"horizon\", service=~\".+-$clouds-.+\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Nova CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_cpu_percent{plugin_instance=~\"nova.*\", service=~\".+-$clouds-.+\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Nova Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_memory{plugin_instance=~\"nova.*\", service=~\".+-$clouds-.+\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceilometer CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_cpu_percent{plugin_instance=~\"ceilometer.*\", service=~\".+-$clouds-.+\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceilometer Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_memory{plugin_instance=~\"ceilometer.*\", service=~\".+-$clouds-.+\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Project $projects",
   "type": "grafana-polystat-panel",
   "description": "Click instance for drill down view",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "repeat": "projects",
   "targets": [
    {
     "expr": "sum by (resource, plugin_instance) (label_replace(collectd_virt_memory{service=~\".+-$clouds-.+\"}, \"resource\", \"$1\", \"host\", \".+:(.+):.+\")) + on(resource) group_right(plugin_instance) ceilometer_cpu{project=\"$projects\", service=~\".+-$clouds-.+\"}",
     "legendFormat": "{{plugin_instance}}"
    }
   ]
  }
 ]
}