{
 "title": "Cloud Infrastructure Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (host) (collectd_cpu_percent{type_instance!=\"idle\"}) / sum by (host) (collectd_cpu_count))",
     "legendFormat": "{{host}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "CPU Saturation (load1 per CPU)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_load_shortterm) / sum by (host) (collectd_cpu_count)\n",
     "legendFormat": "{{host}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (host) (collectd_memory{type_instance=\"used\"})) / (sum by (host) (collectd_memory))",
     "legendFormat": "{{host}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (rate(collectd_vmem_vmpage_faults_majflt_total[1m]))",
     "legendFormat": "{{host}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Net Utilisation (Bytes Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (rate(collectd_interface_if_octets_rx_total{plugin_instance!=\"lo\"}[1m]))",
     "legendFormat": "{{host}} Receive",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "sum by (host) (rate(collectd_interface_if_octets_tx_total{plugin_instance!=\"lo\"}[1m]))",
     "legendFormat": "{{host}} Transmit",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Net Saturation (Drops Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (rate(collectd_interface_if_dropped_rx_total{plugin_instance!=\"lo\"}[1m]))",
     "legendFormat": "{{host}} Receive",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "sum by (host) (rate(collectd_interface_if_dropped_tx_total{plugin_instance!=\"lo\"}[1m]))",
     "legendFormat": "{{host}} Transmit",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host,plugin_instance) (rate(collectd_disk_disk_io_time_io_time_total[1m]))",
     "legendFormat": "{{host}} {{plugin_instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host,plugin_instance) (rate(collectd_disk_disk_io_time_weighted_io_time_total[1m]))",
     "legendFormat": "{{host}} {{plugin_instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  }
 ]
}