apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: service-telemetry-grafanadatasource
  namespace: service-telemetry
spec:
  datasources:
    - name: es_collectd
      access: proxy
      editable: true
      isDefault: false
      url: 'https://elasticsearch-es-http:9200'
      type: elasticsearch
      basicAuth: true
      basicAuthUser: elastic
      basicAuthPassword: ES_PASSWORD
      database: collectd_*
      jsonData:
        tlsSkipVerify: true
        timeField: startsAt
        esVersion: 70
        
    - name: es_ceilometer
      access: proxy
      editable: true
      isDefault: false
      url: 'https://elasticsearch-es-http:9200'
      type: elasticsearch
      basicAuth: true
      basicAuthUser: elastic
      basicAuthPassword: ES_PASSWORD
      database: ceilometer_*
      jsonData:
        tlsSkipVerify: true
        timeField: startsAt
        esVersion: 70

    - name: STFPrometheus
      type: prometheus
      access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      url: 'http://prometheus-operated:9090'
      version: 1
  name: service-telemetry-datasources.yaml
