{
 "title": "Cloud View",
 "tags": [ "CloudView" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 } },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Horizon CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "collectd_libpodstats_pod_cpu_percent{plugin_instance=\"horizon\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Horizon Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "collectd_libpodstats_pod_memory{plugin_instance=\"horizon\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceph CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_cpu_percent{plugin_instance=~\"ceph-.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceph Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_memory{plugin_instance=~\"ceph-.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Nova CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_cpu_percent{plugin_instance=~\"nova.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Nova Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_memory{plugin_instance=~\"nova.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceilometer CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_cpu_percent{plugin_instance=~\"ceilometer.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ceilometer Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (collectd_libpodstats_pod_memory{plugin_instance=~\"ceilometer.*\"})",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}